# Generated by Django 6.1 on 2026-08-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_visible_password',
            field=models.CharField(blank=True, default='', help_text='Demo-only: last plain password set by admin (viewable).', max_length=128),
        ),
    ]
