# Generated by Django 6.1 on 2026-08-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_admin_visible_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_admission',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
