# Generated by Django 5.1.15 on 2026-08-26 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('OFFICE', 'Office'), ('PLACEMENT', 'Placement'), ('PTA', 'PTA'), ('BUS', 'Bus Maintenance'), ('LAB', 'Lab'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('STAFF_ADVISOR', 'Staff Advisor'), ('HOD', 'HOD'), ('PRINCIPAL', 'Principal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=15)),
                ('remark', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sections', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='submissions.submission')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('submission', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('OFFICE', 'Office'), ('PLACEMENT', 'Placement'), ('PTA', 'PTA'), ('BUS', 'Bus Maintenance'), ('LAB', 'Lab'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('STAFF_ADVISOR', 'Staff Advisor'), ('HOD', 'HOD'), ('PRINCIPAL', 'Principal')], max_length=20)),
                ('action', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=15)),
                ('to_status', models.CharField(blank=True, max_length=15)),
                ('remark', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='submissions.submission')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('section_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.sectionstatus')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('OFFICE', 'Office'), ('PLACEMENT', 'Placement'), ('PTA', 'PTA'), ('BUS', 'Bus Maintenance'), ('LAB', 'Lab'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('STAFF_ADVISOR', 'Staff Advisor'), ('HOD', 'HOD'), ('PRINCIPAL', 'Principal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NOT_REQUIRED', 'Not Required')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL)),
                ('section_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='submissions.sectionstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
